// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package newset

import (
	"github.com/plh97/wire-learn/core"
)

// Injectors from wire.go:

func InitUserApi() *UserApi {
	db := core.NewDB()
	logger := core.NewLogger()
	userService := NewUserService(db, logger)
	userApi := NewUserApi(userService)
	return userApi
}
