// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/plh97/wire-learn/api"
	"github.com/plh97/wire-learn/core"
	"github.com/plh97/wire-learn/router"
	"github.com/plh97/wire-learn/service"
)

// Injectors from wire.go:

func InitWire() *gin.Engine {
	logger := core.NewLogger()
	db := core.NewDB()
	userService := service.NewUserService(db, logger)
	videoService := service.NewVideoService(db, logger)
	userApi := api.NewUserApi(logger, userService, videoService)
	videoApi := api.NewVideoApi(userService, videoService)
	engine := router.NewRouter(userApi, videoApi)
	return engine
}
