// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bind

import (
	"github.com/plh97/wire-learn/core"
)

// Injectors from wire.go:

func InitUserService() ServiceInterface {
	db := core.NewDB()
	logger := core.NewLogger()
	serviceInterface := NewUserService(db, logger)
	return serviceInterface
}
