// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package _struct

import (
	"github.com/plh97/wire-learn/core"
)

// Injectors from wire.go:

func InitUserApi() *UserApi {
	db := core.NewDB()
	logger := core.NewLogger()
	userService := NewUserService(db, logger)
	videoService := NewVideoService(db, logger)
	userApi := &UserApi{
		UserService:  userService,
		VideoService: videoService,
	}
	return userApi
}

func InitUserApi1() *UserApi {
	db := core.NewDB()
	logger := core.NewLogger()
	userService := &UserService{
		db:  db,
		log: logger,
	}
	videoService := &VideoService{
		db:  db,
		log: logger,
	}
	userApi := &UserApi{
		UserService:  userService,
		VideoService: videoService,
	}
	return userApi
}
